sylius_shop:
  checkout_resolver:
    enabled: false

nedac_sylius_minimum_order_value:
  checkout_resolver:
    pattern: /checkout/.+
    route_map:
      empty_order:
        route: sylius_shop_cart_summary
      cart:
        route: sylius_shop_checkout_address
      addressed:
        route: sylius_shop_checkout_select_shipping
      shipping_selected:
        route: sylius_shop_checkout_select_payment
      shipping_skipped:
        route: sylius_shop_checkout_select_payment
      payment_selected:
        route: sylius_shop_checkout_complete
      payment_skipped:
        route: sylius_shop_checkout_complete

winzou_state_machine:
  sylius_order_checkout:
    callbacks:
      guard:
        minimum_order_amount_reached:
          on: ['address', 'skip_shipping', 'select_shipping', 'skip_payment', 'select_payment', 'complete']
          do: ['@nedac.sylius_minimum_order_value_plugin.state_machine.guard.minimum_order_value_reached', 'isMinimumOrderValueReached']
          args: ['object']
